//export const SESSION_SECRET=process.env.SESSION_SECRET ?? "super-duper-s3cret"
//export const OAUTH_URL = process.env.OAUTH_URL ?? 'google.com';
//export const CLIENT_ID = process.env.CLIENT_ID ?? 'mysecret-client-id';
//export const CLIENT_SECRET = process.env.CLIENT_SECRET ?? 'mysecret-client-secret';
//export const OAUTH_SCOPE = process.env.OAUTH_SCOPE ?? 'mysecret-scope';
//export const INTRANET_API = process.env.IDENTIFICATION_API ?? 'youtube.com';

export const SESSION_SECRET = process.env.SESSION_SECRET ?? "super-duper-s3cret"
export const OAUTH_URL = process.env.OAUTH_SERVER_URL ?? "api";
export const CLIENT_ID = process.env.CLIENT_ID ?? "mysecret-client-id"
export const CLIENT_SECRET = process.env.CLIENT_SECRET ?? 'mysecret-client-secret';
export const OAUTH_SCOPE = process.env.OAUTH_SCOPE ?? 'mysecret-scope';
export const API_URL = process.env.API_URL ?? 'google.com';
export const FINSCANN_TEST_API = process.env.FINSCANN_TEST_API ?? 'google.com';
export const FINSCANN_API = process.env.FINSCANN_API ?? 'google.com';
export const USERNAME = process.env.USERNAME ?? 'google.com';
export const PASSWORD = process.env.PASSWORD ?? 'google.com';
export const ORGANIZATIONNAME = process.env.ORGANIZATIONNAME ?? 'google.com';
export const APPLICATIONID = process.env.APPLICATIONID ?? 'google.com';